- hosts: db_servers
  tasks:
  - name: Add MySQL repo
    yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm state=present
  - name: Install MySQL
    yum: name={{ item }} update_cache=yes state=installed
    with_items:
      - mysql
      - mysql-server
  - name: Enable Epel
    yum:
      name: epel-release
      state: latest
  - name: Install pip
    yum:
      name: python-pip
      state: latest
  - name: Install the Python MySQLB module
    pip: name=MySQL-python
  - name: Update mysql root password for all root accounts "{{ dbpass }}"
    mysql_user: name=root password="{{ dbpass }}" priv="*.*:ALL,GRANT"