- hosts: db_servers
  tasks:
  - name: Add MySQL repo
    yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm state=present
  - name: Install MySQL
    yum: name={{ item }} update_cache=yes state=installed
    with_items:
      - mysql
      - mysql-server
  - name: Enable Epel
    yum:
      name: epel-release
      state: latest
  - name: Install Python-devel
    yum:
      name: python-devel
      state: latest
  - name: Install Mysql-devel
    yum:
      name: mysql-devel
      state: latest
  - name: Install gcc
    yum:
      name: gcc
      state: latest
  - name: Install pip
    yum:
      name: python-pip
      state: latest
  - name: Ensure mysql started
    service:
      name: mysqld
      state: started
      enabled: yes
  - name: Install the Python MySQLB module
    pip: name=MySQL-python
  - name: update mysql root password for all root accounts
    sudo: yes
    mysql_user: 
      name: root 
      host: "{{ item }}" 
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost 