- hosts: db_servers
  tasks:
  - name: Add MySQL repo
    yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm state=present
  - name: Install MySQL
    yum: name={{ item }} update_cache=yes state=installed
    with_items:
      - mysql
      - mysql-server
  - name: Update mysql root password for all root accounts "{{ dbpass }}"
    mysql_user: name=root password="{{ dbpass }}" priv="*.*:ALL,GRANT"