- hosts: kms_servers
  tasks:
  - name: Task info
    debug:
      msg: "Vanilla install KMS 4.6.1 on {{hostname}}, IP {{ ansible_ssh_host }}"
  - name: Update system
    yum: name='*' state=latest
  - name: Create folder for installation files
    file: 
      path: /usr/local/install
      state: directory
      mode: 0755
  - name: Create folder for tomcat kms
    file:
      path: /usr/local/tomcat7-kms
      state: directory
      mode: 0755
  - name: Create folder for tomcat solr
    file:
      path: /usr/local/tomcat7-solr
      state: directory
      mode: 0755
  - name: Copy java 1.7
    copy:
      src: /usr/local/install/4.6.1/jdk-7u80-linux-x64.rpm
      dest: /usr/local/install
      mode: 0755
  - name: install java 1.7
    yum:
      name: /usr/local/install/jdk-7u80-linux-x64.rpm
      state: latest
  - name: Install httpd
    yum:
      name: httpd
      state: latest
  - name: Copy mod_jk module for httpd
    copy:
      src: /usr/local/install/modules/mod_jk.so
      dest: /usr/lib64/httpd/modules/mod_jk.so
  - name: Copy configs for httpd
    copy:
      src: /usr/local/install/httpd/
      dest: /etc/httpd
  - name: Download zabbix rpm (zabbix version 3.010)
    get_url:
      url: http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-agent-3.0.10-1.el7.x86_64.rpm 
      dest: /usr/local/install/zabbix-agent-3.0.10-1.el7.x86_64.rpm 
      mode: 0755
  - name: Install zabbix-agent
    yum:
      name: /usr/local/install/zabbix-agent-3.0.10-1.el7.x86_64.rpm
      state: latest
  - name: Create folder for zabbix
    file: 
      path: /opt/zabbix
      state: directory
      mode: 0755
  - name: Copy zabbix config 1
    copy:
      src: /usr/local/install/zabbix/zabbix_agent_app/zabbix/
      dest: /etc/zabbix/
  - name: Copy zabbix config 2
    copy:
      src: /usr/local/install/zabbix/zabbix_agent_app/opt/zabbix/
      dest: /opt/zabbix/
  - name: Setup zabbix (zabbix_agentd.conf)
    replace:
      dest: /etc/zabbix/zabbix_agentd.conf
      regexp: 'ansible_app 127.0.0.1'
      replace: '{{ hostname }} {{ ansible_ssh_host }}'
- hosts: db_servers
  tasks:
  - name: Task info
    debug:
      msg: "Vanilla DB installation KMS 4.6.1 on {{hostname}}, IP {{ ansible_ssh_host }}"
  - name: Create installation folder
    file: 
      path: /usr/local/install
      state: directory
      mode: 0755
  - name: Copy installer 4.6.1
    copy:
      src: /ansible/4.6.1/installer.jar
      dest: /usr/local/install
      mode: 0755
  - name: Download zabbix rpm (zabbix version 3.010)
    get_url:
      url: http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-agent-3.0.10-1.el7.x86_64.rpm 
      dest: /usr/local/install/zabbix-agent-3.0.10-1.el7.x86_64.rpm 
      mode: 0755
  - name: Install zabbix-agent
    yum:
      name: /usr/local/install/zabbix-agent-3.0.10-1.el7.x86_64.rpm
      state: latest
  - name: Create folder for zabbix
    file: 
      path: /opt/zabbix
      state: directory
      mode: 0755
  - name: Copy zabbix config 1
    copy:
      src: /usr/local/install/zabbix/zabbix_agent_db/zabbix/
      dest: /etc/zabbix/
  - name: Copy zabbix config 2
    copy:
      src: /usr/local/install/zabbix/zabbix_agent_db/opt/zabbix/
      dest: /opt/zabbix/
  - name: Setup zabbix (zabbix_agentd.conf)
    replace:
      dest: /etc/zabbix/zabbix_agentd.conf
      regexp: 'ansible_db 127.0.0.1'
      replace: '{{ hostname }} {{ ansible_ssh_host }}'