- hosts: kms_servers
  tasks:
  - name: copy java
    copy:
      src: /ansible/4.6.1/jdk-7u80-linux-x64.rpm
      dest: /usr/local/
      mode: 0755
  - name: install java 1.7
    yum:
      name: /usr/local/jdk-7u80-linux-x64.rpm
      state: latest
  - name: install httpd
    yum:
      name: httpd
      state: latest
- hosts: db_servers
  tasks:
  - name: copy java
    copy:
      src: /ansible/4.6.1/installer.jar
      dest: /usr/local/
      mode: 0755